# 可视化配置
visualization:
  # 图表样式配置
  style:
    figure_size: [12, 8]
    dpi: 300
    color_palette: "viridis"
    font_family: "SimHei"
    
  # 热力图配置
  heatmap:
    time_bins: 24  # 24小时
    color_scheme: "YlOrRd"
    annotate: true
    
  # 留存曲线配置
  retention:
    periods: [1, 3, 7, 14, 30]  # 留存周期（天）
    line_style: "o-"
    line_width: 2
    
  # 用户分群配置
  segmentation:
    scatter_size: 50
    alpha: 0.6
    legend_position: "upper right"
    
  # 输出配置
  output:
    format: ["png", "pdf"]
    path: "./outputs/charts"
    quality: "high"
    
# Superset配置
superset:
  host: "localhost"
  port: 8088
  database_name: "video_analysis"
  dashboard_title: "视频平台RFM分析仪表板"
